// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTY-lJ_3XtXj8CffEMB-Te7j2DqeHTNDQ',
    appId: '1:1048647948872:ios:1ade8b1e6633e368b2567d',
    messagingSenderId: '1048647948872',
    projectId: 'device-streaming-8800428e',
    storageBucket: 'device-streaming-8800428e.firebasestorage.app',
    iosBundleId: 'com.tsukiapp.tsukiApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlmBnBnTfWRvkf2pLb70oiImskDzoiT-Q',
    appId: '1:337578395985:android:78a4a0f370e9a7ffd0ab70',
    messagingSenderId: '337578395985',
    projectId: 'petit-works-utility',
    storageBucket: 'petit-works-utility.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFrJX-vHDV6nB0w4dTWPHHPTcoEFr8js',
    appId: '1:1048647948872:web:6437c59982eceb8db2567d',
    messagingSenderId: '1048647948872',
    projectId: 'device-streaming-8800428e',
    authDomain: 'device-streaming-8800428e.firebaseapp.com',
    storageBucket: 'device-streaming-8800428e.firebasestorage.app',
  );
}
